version: '3'
services:
  pioneer_simulation:
    build:
      context: ./
      dockerfile: docker/pioneer/Dockerfile
    image: pioneer_simulation
    user: ros
    network_mode: host
    ipc: host
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - CYCLONEDDS_URI=${CYCLONEDDS_URI}
      - ROS_DOMAIN_ID
    volumes:
      - ./cyclonedds_ariadna.xml:/cyclonedds.xml
      - ./src:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true 
    tty: true
    command:  ros2 launch pioneer_cyton_description spawn_robot.launch.py